export const card =[
    {
      title:"Sary-Chelek",
      img:"",
      price:"3000s",
    },
    {
        title:"Sary-Chelek",
        img:"",
        price:"3000s",
      },
      {
        title:"Sary-Chelek",
        img:"",
        price:"3000s",
      },
      {
        title:"Sary-Chelek",
        img:"",
        price:"3000s",
      },
      {
        title:"Sary-Chelek",
        img:"",
        price:"3000s",
      },
      {
        title:"Sary-Chelek",
        img:"",
        price:"3000s",
      },
      {
        title:"Sary-Chelek",
        img:"",
        price:"3000s",
      },
      {
        title:"Sary-Chelek",
        img:"",
        price:"3000s",
      },
      {
        title:"Sary-Chelek",
        img:"",
        price:"3000s",
      }
  ]